name: LightCutter
version: '1.3.0'
main: ru.kainlight.lightcutter.Main
api-version: 1.16
depend: [ WorldGuard, PlaceholderAPI, Vault ]
softdepend: [ PlayerPoints ]
authors: [ kainlight ]
website: https://github.com/kainlighty

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.20
  - com.zaxxer:HikariCP:5.1.0
  - net.kyori:adventure-api:4.17.0
  - net.kyori:adventure-platform-bukkit:4.3.4

commands:
  lightcutter:
    permission: lightcutter.help
    aliases:
      - lc

permissions:
  lightcutter.help:
    default: op
  lightcutter.add:
    default: op
  lightcutter.update:
    default: op
  lightcutter.remove:
    default: op
  lightcutter.info:
    default: op
  lightcutter.reload:
    default: op
  lightcutter.break.bypass:
    default: op
  lightcutter.modes.bypass:
    default: op
  lightcutter.cooldown.bypass:
    default: op
  lightcutter.bypass.*:
    default: op
    children:
      lightcutter.modes.bypass: true
      lightcutter.cooldown.bypass: true
      lightcutter.break.bypass: true
  lightcutter.admin:
    children:
      lightcutter.bypass.*: true
      lightcutter.help: true
      lightcutter.add: true
      lightcutter.update: true
      lightcutter.remove: true
      lightcutter.info: true
      lightcutter.reload: true
