name: LightCutter
version: ${pluginVersion}
main: ru.kainlight.lightcutter.Main
api-version: 1.16
depend: [ WorldGuard, Vault ]
softdepend: [ PlayerPoints, CMI ]
loadbefore: [ WorldGuard ]
authors: [ kainlight ]
website: https://github.com/kainlighty

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
  - com.zaxxer:HikariCP:${hikariCPVersion}
  - net.kyori:adventure-api:${adventureVersion}
  - net.kyori:adventure-text-minimessage:${adventureVersion}
  - net.kyori:adventure-platform-bukkit:${adventureBukkitVersion}
  - com.mysql:mysql-connector-j:${mysqlVersion}

commands:
  lightcutter:
    permission: lightcutter.help
    aliases:
      - lc

permissions:
  lightcutter.help:
    default: op
  lightcutter.add:
    default: op
  lightcutter.update:
    default: op
  lightcutter.remove:
    default: op
  lightcutter.info:
    default: op
  lightcutter.reload:
    default: op
  lightcutter.modes.bypass:
    default: op
  lightcutter.cooldown.bypass:
    default: op
  lightcutter.bypass.*:
    default: op
    children:
      lightcutter.modes.bypass: true
      lightcutter.cooldown.bypass: true
  lightcutter.admin:
    children:
      lightcutter.help: true
      lightcutter.add: true
      lightcutter.update: true
      lightcutter.remove: true
      lightcutter.info: true
      lightcutter.reload: true
      lightcutter.bypass.*: true
