name: LightCutter
version: '1.2.4'
main: ru.kainlight.lightcutter.Main
api-version: 1.13
depend: [ WorldGuard, PlaceholderAPI, Vault ]
softdepend: [ PlayerPoints ]
authors: [ kainlight ]
website: https://github.com/kainlighty

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23
  - com.zaxxer:HikariCP:5.1.0

commands:
  lightcutter:
    permission: lightcutter.admin
    aliases:
      - lc

permissions:
  lightcutter.modes.bypass:
    default: op
  lightcutter.cooldown.bypass:
    default: op
  lightcutter.bypass.*:
    default: op
    children:
      lightcutter.modes.bypass: true
      lightcutter.cooldown.bypass: true
  lightcutter.admin:
    children:
      lightcutter.bypass.*: true